[toolchain]
channel = "stable"
components = [
    "cargo",
    "clippy",
    "rust-src",
    "rustc",
    "rustfmt"
]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-gnu"
]